apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJiV1ZuWVd4dmMyRnVaSEp2Y3pwbmFYUm9kV0pmY0dGMFh6RXhRVGRMUnpKVFFUQkROVEoxUVdkclpGUXlaRU5mUWxWd2RYWnBPSEpqUWpoT05YSk9ZVmhFVGtkU1JXTnpXR3hUWlc1eWRGTkxlbXRUYVRkVVRHZzVRVTlMTkU1UFdsSldiV3M1Y3pSME9Xaz0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
